# Generated by Django 6.0.1 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=100)),
                ('is_adpoted', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['age'],
                'indexes': [models.Index(fields=['age'], name='shelter_ani_age_2c149a_idx')],
            },
        ),
    ]
