# Generated by Django 6.0.1 on 2026-01-19 17:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_img'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
