# Generated by Django 6.0.1 on 2026-01-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_alter_animal_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='is_adpoted',
            new_name='is_adopted',
        ),
    ]
