# Generated by Django 6.0.2 on 2026-03-30 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_animal_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter_name', models.CharField(max_length=100)),
                ('adoption_date', models.DateField(default=django.utils.timezone.now)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAnimalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('walker', 'Dog Walker'), ('feeder', 'Feeder'), ('trainer', 'Trainer'), ('medical', 'Medical Assistant')], default='walker', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'animal')},
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='animals',
            field=models.ManyToManyField(related_name='volunteers', through='shelter.VolunteerAnimalCare', to='shelter.animal'),
        ),
    ]
